/**
 * Bridge Client — WebSocket-based navigator.modelContext implementation
 *
 * This module provides a polyfill for navigator.modelContext that routes
 * tool registrations and executions through a WebSocket connection to
 * the webmcp-anything Bridge server.
 *
 * When native WebMCP (navigator.modelContext) is available, it's used directly.
 * When not, this client installs a Bridge-backed implementation so that
 * existing `useWebMCP` hooks work without any code changes.
 */

export interface BridgeClientOptions {
  /** WebSocket URL of the Bridge server. Default: ws://localhost:9100 */
  url?: string;
  /** Application identifier. Used as prefix in multi-tab scenarios */
  appId?: string;
  /** Auth token for the Bridge (generated by Bridge on startup) */
  token?: string;
  /** Reconnection settings */
  reconnect?: {
    /** Enable auto-reconnect. Default: true */
    enabled?: boolean;
    /** Initial delay in ms. Default: 1000 */
    initialDelay?: number;
    /** Max delay in ms. Default: 30000 */
    maxDelay?: number;
  };
  /** Force Bridge mode even if native WebMCP is available. Default: false */
  forceBridge?: boolean;
  /** Callback when connection state changes */
  onConnectionChange?: (connected: boolean) => void;
}

interface PendingCall {
  resolve: (result: unknown) => void;
  reject: (error: Error) => void;
  timeout: ReturnType<typeof setTimeout>;
}

interface RegisteredTool {
  name: string;
  description: string;
  inputSchema?: object;
  outputSchema?: object;
  annotations?: object;
  execute: (args: object, client?: unknown) => Promise<unknown>;
}

type ToolsChangedCallback = (() => void) | null;

/**
 * BridgeModelContext — implements the same interface as navigator.modelContext
 * but routes everything through WebSocket to the Bridge server.
 */
class BridgeModelContext {
  private ws: WebSocket | null = null;
  private tools = new Map<string, RegisteredTool>();
  private pendingCalls = new Map<string, PendingCall>();
  private toolsChangedCallback: ToolsChangedCallback = null;
  private callIdCounter = 0;
  private reconnectDelay: number;
  private reconnectTimer: ReturnType<typeof setTimeout> | null = null;
  private intentionalClose = false;
  private tabId: string | null = null;
  private connected = false;

  constructor(private options: Required<BridgeClientOptions>) {
    this.reconnectDelay = options.reconnect.initialDelay ?? 1000;
  }

  // ── Public API (matches navigator.modelContext interface) ──

  registerTool(tool: RegisteredTool): { unregister: () => void } {
    if (this.tools.has(tool.name)) {
      throw new Error(`Tool already registered: ${tool.name}`);
    }

    this.tools.set(tool.name, tool);
    this.sendToolsUpdated();

    return {
      unregister: () => {
        this.tools.delete(tool.name);
        this.sendToolsUpdated();
      },
    };
  }

  unregisterTool(name: string): void {
    if (this.tools.delete(name)) {
      this.sendToolsUpdated();
    }
  }

  // ── Connection Management ──

  connect(): void {
    if (this.ws?.readyState === WebSocket.OPEN) return;

    const url = new URL(this.options.url);
    if (this.options.token) {
      url.searchParams.set('token', this.options.token);
    }

    this.ws = new WebSocket(url.toString());

    this.ws.onopen = () => {
      this.connected = true;
      this.reconnectDelay = this.options.reconnect.initialDelay ?? 1000;
      this.options.onConnectionChange?.(true);

      // Send register message with current tool list
      this.send({
        type: 'register',
        appId: this.options.appId,
        url: globalThis.location?.href ?? '',
        tools: this.serializeTools(),
      });
    };

    this.ws.onmessage = (event) => {
      try {
        const msg = JSON.parse(event.data as string);
        this.handleMessage(msg);
      } catch {
        console.warn('[webmcp-anything] Failed to parse Bridge message');
      }
    };

    this.ws.onclose = () => {
      this.connected = false;
      this.options.onConnectionChange?.(false);

      // Reject all pending calls
      for (const [callId, pending] of this.pendingCalls) {
        clearTimeout(pending.timeout);
        pending.reject(new Error('Bridge connection closed'));
        this.pendingCalls.delete(callId);
      }

      // Auto-reconnect unless intentionally closed
      if (!this.intentionalClose && this.options.reconnect.enabled !== false) {
        this.scheduleReconnect();
      }
    };

    this.ws.onerror = () => {
      // onclose will fire after onerror, so reconnect is handled there
    };
  }

  disconnect(): void {
    this.intentionalClose = true;
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
    this.ws?.close();
    this.ws = null;
  }

  isConnected(): boolean {
    return this.connected;
  }

  getTabId(): string | null {
    return this.tabId;
  }

  // ── Private ──

  private handleMessage(msg: Record<string, unknown>): void {
    switch (msg.type) {
      case 'registered':
        this.tabId = msg.tabId as string;
        break;

      case 'execute_tool':
        this.handleExecuteTool(msg);
        break;

      default:
        console.warn(`[webmcp-anything] Unknown Bridge message type: ${msg.type}`);
    }
  }

  private async handleExecuteTool(msg: Record<string, unknown>): Promise<void> {
    const callId = msg.callId as string;
    const toolName = msg.name as string;
    const args = (msg.arguments ?? {}) as object;

    const tool = this.tools.get(toolName);
    if (!tool) {
      this.send({
        type: 'tool_error',
        callId,
        error: `Tool not found: ${toolName}`,
      });
      return;
    }

    try {
      const result = await tool.execute(args);
      this.send({
        type: 'tool_result',
        callId,
        result,
      });
    } catch (err) {
      this.send({
        type: 'tool_error',
        callId,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  private sendToolsUpdated(): void {
    if (!this.connected) return;
    this.send({
      type: 'tools_updated',
      tools: this.serializeTools(),
    });
    // Notify any listeners (matches the polyfill's toolsChangedCallback pattern)
    if (this.toolsChangedCallback) {
      queueMicrotask(() => this.toolsChangedCallback?.());
    }
  }

  private serializeTools(): object[] {
    return [...this.tools.values()].map((tool) => ({
      name: tool.name,
      description: tool.description,
      ...(tool.inputSchema ? { inputSchema: tool.inputSchema } : {}),
      ...(tool.outputSchema ? { outputSchema: tool.outputSchema } : {}),
      ...(tool.annotations ? { annotations: tool.annotations } : {}),
    }));
  }

  private send(data: object): void {
    if (this.ws?.readyState === WebSocket.OPEN) {
      this.ws.send(JSON.stringify(data));
    }
  }

  private scheduleReconnect(): void {
    if (this.reconnectTimer) return;

    this.reconnectTimer = setTimeout(() => {
      this.reconnectTimer = null;
      this.reconnectDelay = Math.min(
        this.reconnectDelay * 2,
        this.options.reconnect.maxDelay ?? 30000,
      );
      this.connect();
    }, this.reconnectDelay);
  }

  private nextCallId(): string {
    return `call_${++this.callIdCounter}_${Date.now()}`;
  }
}

// ── Public API ──

let bridgeInstance: BridgeModelContext | null = null;

/**
 * Initialize the Bridge client.
 *
 * - If native navigator.modelContext exists and forceBridge is false, does nothing.
 * - Otherwise, creates a BridgeModelContext and installs it as navigator.modelContext.
 *
 * This means existing `useWebMCP()` hooks work without any code changes —
 * they register Tools on navigator.modelContext which is transparently backed
 * by the Bridge WebSocket connection.
 */
export function initBridge(options: BridgeClientOptions = {}): BridgeModelContext | null {
  const nav = typeof navigator !== 'undefined' ? navigator : null;

  // If native WebMCP exists and we're not forcing Bridge mode, skip
  if (nav?.modelContext && !options.forceBridge) {
    console.info('[webmcp-anything] Native WebMCP detected, using navigator.modelContext directly');
    return null;
  }

  const resolved: Required<BridgeClientOptions> = {
    url: options.url ?? 'ws://localhost:9100',
    appId: options.appId ?? guessAppId(),
    token: options.token ?? '',
    reconnect: {
      enabled: options.reconnect?.enabled ?? true,
      initialDelay: options.reconnect?.initialDelay ?? 1000,
      maxDelay: options.reconnect?.maxDelay ?? 30000,
    },
    forceBridge: options.forceBridge ?? false,
    onConnectionChange: options.onConnectionChange ?? (() => {}),
  };

  bridgeInstance = new BridgeModelContext(resolved);

  // Install as navigator.modelContext polyfill
  if (nav) {
    Object.defineProperty(nav, 'modelContext', {
      configurable: true,
      enumerable: true,
      writable: false,
      value: bridgeInstance,
    });
  }

  // Connect
  bridgeInstance.connect();

  return bridgeInstance;
}

/**
 * Disconnect and remove the Bridge client.
 */
export function cleanupBridge(): void {
  if (bridgeInstance) {
    bridgeInstance.disconnect();
    bridgeInstance = null;
  }

  // Remove the polyfill
  const nav = typeof navigator !== 'undefined' ? navigator : null;
  if (nav) {
    try {
      delete (nav as unknown as Record<string, unknown>).modelContext;
    } catch {
      // Ignore if not deletable
    }
  }
}

/**
 * Get the current Bridge client instance (if initialized).
 */
export function getBridge(): BridgeModelContext | null {
  return bridgeInstance;
}

// ── Helpers ──

function guessAppId(): string {
  if (typeof document !== 'undefined' && document.title) {
    return document.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 32) || 'webapp';
  }
  return 'webapp';
}
